locations:
  spawn:
    world: BuildGuessLobby
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0
  buildspace:
    world: BuildGuessLobby
    x: 0.0
    y: 0.0
    z: 0.0
    yaw: 0.0
    pitch: 0.0